name: ashfall_visual
channels:
  - bokeh/channel/dev
  - defaults
dependencies:
  - bokeh=0.12.16dev2
  - cartopy=0.15.*
  - colorcet=1.0.*
  - geopy=1.13.*
  - geoviews=1.4.*
  - holoviews=1.9.*
  - matplotlib=2.2.*
  - numpy=1.14.*
  - pyproj=1.9.*
  - xarray=0.10.*
  - pip:
    - fastkml==0.11