name: ashfall_visual
channels:
  - pyviz/label/dev 
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - pyviz=0.9.*
  - colorcet=1.0.*
  - esmpy=7.1.*
  - fiona=1.8.*
  - geopy=1.13.*
  - pyproj=1.9.*
  - rasterio=1.*
  - pip:
    - simplekml==1.2.*
    - xesmf==0.1.*

