name: ashfall_visual
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=0.13.0
  - cartopy=0.15.1
  - colorcet=1.0.0
  - esmpy=7.1.0
  - fiona=1.7.11
  - gdal=2.2.4
  - geopy=1.13.0
  - geoviews=1.4.3
  - holoviews=1.9.5
  - matplotlib=2.2.2
  - netcdf4=1.3.1
  - numpy=1.14.6
  - pyproj=1.9.5.1
  - rasterio=0.36.0
  - xarray=0.10.4
  - pip:
    - simplekml==1.2.8
    - xesmf==0.1.1