name: ashfall_visual
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh
  - cartopy
  - colorcet
  - esmpy
  - fiona
  - gdal
  - geopy
  - geoviews
  - holoviews
  - matplotlib
  - netcdf
  - numpy
  - pyproj
  - rasterio
  - xarray
  - pip:
    - simplekml
    - xesmf