name: ashfall_visual
channels:
  - conda-forge
  - defaults
dependencies:
  - bokeh=0.13.*
  - cartopy=0.15.*
  - colorcet=1.0.*
  - esmpy=7.1.*
  - fiona=1.7.*
  - gdal=2.2.*
  - geopy=1.13.*
  - geoviews=1.4.*
  - holoviews=1.9.*
  - matplotlib=2.2.*
  - netcdf4=1.3.*
  - numpy=1.14.*
  - pyproj=1.9.*
  - rasterio=0.36.*
  - xarray=0.10.*
  - pip:
    - simplekml==1.2.*
    - xesmf==0.1.*