name: ashfall_visual
channels:
  - bokeh/channel/dev
  - conda-forge
  - defaults
dependencies:
  - bokeh=0.12.16dev2
  - cartopy=0.15.*
  - colorcet=1.0.*
  - fiona=1.7.*
  - gdal=2.2.*
  - geopy=1.13.*
  - geoviews=1.4.*
  - holoviews=1.9.*
  - matplotlib=2.2.*
  - netcdf4=1.3.*
  - numpy=1.14.*
  - pyproj=1.9.*
  - rasterio=0.36.*
  - shapely=1.6.*
  - xarray=0.10.*
  - pip:
    - simplekml==1.2.*